print(ord("S")-ord("D"))
def CaeserCipher(ciphertext,key):
    A = 65
    plaintext = ""
    for each in ciphertext:
        plaintext += chr((ord(each)+key-A)%26+A)
    return plaintext

str1 = "STLAEOTQQIMQPKAVDHLMDXWIJLZZEQJXEIEBPYEMCXKVPAZPAYZZHKKPDKYBEHFWLZKMYAJTZOOBHDVUELOKSRWGEHJPLXWLPXZWOLHILLLZHHJMOMAMDKZUFUELEYSMLMCMWLSPLXSQNBLBMMWLDKAQPHKVDYWSFEKBSDVQJXSMT"
str2 = "IYAQUPXUEAMDZHTLCHAZQOPJILXQIEHWPLXEZZHKGDAUKPHWBEHLITLSVDTZKXMJLPMKOPRALZTSWPFSPMTSMAKHPQXWAYTSVOBGJCKKBRMSMAGHGZLEWDHSQZBTWELOZZXOLNBWBQKFMEBZMSKZSPHKWGAAAXHWTWHGMQMFWAKSO"
str3 = "JSPHWIEMZMTEQPXBJEPHFULEFJWMUZXEWBYHLZYIABPXLPWTWAHTKATMLEYXGMSASIXMXTDDATJMMBZBGCDKJIPMSLYKLBOGYBDDMMPRWMZGFTPLGOEXXPWDJCEXCPLAWLXXFWDHLBELKPQTDIDTWXYVXMTYZWAAVGXUEWZZMAPWZ"
str4 = "KKNFPEBFTFIYVQVCXZPWOSAJQGQSASPWKLBCALMPGSDNBGLEWZQYMAJTKZQENGMLZYIPKAMPYMBSEGZDNLDPWYMPAABDBGIOMZWDMSBEKLCJXSFNNWWXKGLPBLERGWVZTAIDHMQCAOWFVWQCBLEGWMISMJXSHFTTNXMLBJPQCOGTM"
str5 = "JYAAPNWZEXEWWTGMTHGLZBUDTNTMPVWAOTLMPTQVRUAWYNLBEHEBZMDBZHKPWGEDCTAIZUWINMGMOKWQRLWNTXFLZYUIXGHASXFPTELPZTYEPGLWEMXJZNSMPMGWZKQPDLAPEGWGPTXZLKFLPKGMSMFISGWMCXWUDBGKWPWZZAGVY"
str6 = "BZEWPNKWPOLLMYMDSTNOTDEWWEKSLEKGMNHGMYLLBWWFODHWPHIAPAXOOZXWLPTWCTLDUCFYWPZJTPHWPSKMIDVOAQBFMDMLMXXSBWRWVWASLZLMZLMWODGFASNGEPHSWWLGLELLBDTSUMWLDZNJQLWFMZOOBJEUCYGCWLTGLLNYW"
str7 = "ZZPGSPAHSJEOSLPRFVDTNQPKMBLMWNDNWPTOXLSMGQPGLMEFWAZMWWETWZOYKQYAVVTBLIDHFLPBAIQLLMJEJECBLMAWOPPKFBWKAGPEWWPRLCEEQTSKWMOJSMWWAEYWFQTNAUEAZXYGWCTHWOWBKBSVYZPTGXTHSLPMGZCFABCKO"

print(CaeserCipher(str1,11))
print((CaeserCipher(str2,22)))
print((CaeserCipher(str3,17)))
print((CaeserCipher(str4,7)))
print((CaeserCipher(str5,)))
print((CaeserCipher(str6,)))
print((CaeserCipher(str7,)))