import numpy as np
from sympy import Matrix

def is_invertible(matrix):
    return np.linalg.matrix_rank(matrix) == len(matrix)

def matrix_mod_inverse(matrix, modulus):
    det = int(np.round(np.linalg.det(matrix)))
    det_inv = pow(det, -1, modulus)  # Using modular inverse

    adjugate = Matrix(matrix).adjugate()
    inverse = (det_inv * adjugate) % modulus

    return np.array(inverse, dtype=int)

def decrypt_hill_cipher(ciphertext, key_matrix, modulus):
    if not is_invertible(key_matrix):
        raise ValueError("Key matrix is not invertible. Decryption is not possible.")

    key_inverse = matrix_mod_inverse(key_matrix, modulus)

    ciphertext = np.array([ord(char) - ord('A') for char in ciphertext.upper()])
    ciphertext = np.reshape(ciphertext, (len(ciphertext) // len(key_matrix), len(key_matrix)))

    decrypted_matrix = (ciphertext.dot(key_inverse)) % modulus
    decrypted_text = ''.join([chr(char + ord('A')) for char in decrypted_matrix.flatten()])

    return decrypted_text

# Example usage:
ciphertext = open("ciphertext.txt","r").read()
key_matrix = np.array([[1,1], [0,1]])
modulus = 26  # Assuming the text is in the English alphabet

plaintext = "JODIE I HAVE MORE OR LESS COMPLETED THE INVESTIGATION HERE AND THOUGHT I SHOULD BRING YOU UP-TO-DATE WITH MY FINDINGS A ROGERS HAD INHERITED THE COLLECTION AND FOLLOWING HER APPOINTMENT NINE YEARS BEFORE THE INCIDENT MAISIE HAD CURATED IT ACQUIRING A LARGE NUMBER OF RARE AND VALUABLE EDITIONS OF AMERICAN TEXTS B FOLLOWING THE INVESTIGATIONS BY HARPER AND MAISIE HERSELF ROGERS WITHDREW FROM THE GUBERNATORIAL RACE AND WROTE TO THE RHODE ISLAND LIBRARY TO TELL THEM THAT HE WAS WITHDRAWING THE OFFER OF HIS COLLECTION HE DID NOT GIVE A REASON AND DID NOT RECEIVE A REPLY FROM THEM AS FAR AS I CAN TELL C ROGERS CONTINUED TO LIVE AT THE MANSION AND DISAPPEARED FROM PUBLIC LIFE HE CONTINUED TO FUND THE EXPANSION OF THE LIBRARY AND MAISIE CONTINUED TO CURATE IT'D UPON HIS DEATH ROGERS LEFT ALMOST HIS ENTIRE ESTATE TO HIS NIECE NANCY WARNE WHO TOOK UP RESIDENCE AT THE MANOR WITH THE CAVEAT THAT MAISIE WAS TO BE ALLOWED TO LIVE WITH HER AND TO MAINTAIN THE LIBRA RYE MAISIE CONTINUED TO LIVE IN THE EAST WING OF THE HOUSE LOOKING AFTER THE LIBRARY UNTIL SHE PASSED AWAY WHEN I GOT THAT FAR I THOUGHT MAYBE WE WERE DONE AND THAT THIS WOULD GO DOWN IN THE ANNALS AS A DEADEND TO BE RETURNED TO THE ARCHAEOLOGY SECTION AS A CURIOSITY RATHER THAN A CLOSED CASE BUT THEN I FOUND A LETTER FROM THE RHODE ISLAND CITY LIBRARY TO NANCYS HE HAD OFFERED THE LIBRARY COLLECTION TO THE CITY FOLLOWING MAISIE'S DEATH AND THEY WERE WRITING TO TELL HER THAT FOLLOWING AN ASSESSMENT OF THE COLLECTION THEY WOULD BE UNABLE TO ACCEPT THE KIND OFFER THE REASON THEIR AUDIT SHOWED THAT MANY OF THE RARE AND VALUABLE ITEMS WERE IN FACT FAKES NO-ONE WAS EVER CONVICTED IN CONNECTION WITH THE BREAK-IN OR ANY CRIME CONNECTED WITH THE FORGERIES I STILL DON'T KNOW WHETHER ROGERS KNEW THE BOOKS WERE FAKE BUT IT SEEMS UNLIKELY GIVEN HIS KEENNESS TO DONATE THEM AS WE KNOW THE FRAUD WAS BOUND TO BE EXPOSED BY THE EXPERTS WORKING AT THE CITY LIBRARY MAYBE ROGERS AND MAISIE WERE VICTIMS OF FRAUD BY BOOKSELLERS BUT THE BOOKS WERE BOUGHT IN SMALL BATCHES AND IT DOESN'T SEEM LIKELY THAT THEY WERE BOTH REPEATEDLY FOOLED IN ANY CASE MAISIE'S BACKGROUND IN BOOK PRESERVATION SHOULD HAVE MADE IT POSSIBLE FOR HER TO SPOT AT LEAST SOME OF THE FAKES THE ENCLOSED LETTER FROM MAISIE TO ROGERS DOESN'T SHED MUCH LIGHT BUT UNTIL I CAN CRACK THE REST OF HER DIARY IT IS ALL I HAVE GOT TO GO ON I FEEL LIKE WE ARE CLOSE TO SOLVING THIS MYSTERY BUT STILL NOT QUITE THERE I HAVE THE ORIGINAL LETTER ON MY DESK BUT FOUND AN ENCRYPTED COPY IN MAISIE'S DIARY AND SINCE IT IS RATHER AN INTERESTING CIPHER I HAVE ATTACHED THAT VERSION FOR THE TRAINEES TO TRY LET ME KNOW IF THEY NEED HELP AND I WILL POST SOMETHING IN THE BOSS FORUM PROBABLY OVER THE WEEKEND HARRY"
plaintext = plaintext.replace(" ","")
print(plaintext)

